-- Receipt identity and line birth/deletion evidence. Header/status/plan effects
-- and complete command attribution require additional independent guards.
CREATE TABLE procurement.order_line_edit_proof (
  root_transaction bigint NOT NULL,
  line_id integer NOT NULL,
  order_id integer NOT NULL,
  action text NOT NULL CHECK(action IN ('add_line','delete_line')),
  snapshot jsonb NOT NULL,
  PRIMARY KEY(root_transaction,line_id,action)
);
CREATE OR REPLACE FUNCTION procurement.guard_line_edit_proof() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF pg_trigger_depth()<>2 OR NEW.root_transaction<>txid_current() THEN
    RAISE EXCEPTION 'Line edit proof must be generated by a line trigger';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER generated_line_edit_proof BEFORE INSERT ON procurement.order_line_edit_proof
FOR EACH ROW EXECUTE FUNCTION procurement.guard_line_edit_proof();
CREATE TRIGGER immutable_line_edit_proof BEFORE UPDATE OR DELETE ON procurement.order_line_edit_proof
FOR EACH ROW EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER no_truncate_line_edit_proof BEFORE TRUNCATE ON procurement.order_line_edit_proof
FOR EACH STATEMENT EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE OR REPLACE FUNCTION procurement.record_line_edit() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE row_value procurement.purchase_order_line;
BEGIN
  IF TG_OP='INSERT' THEN row_value:=NEW; ELSE row_value:=OLD; END IF;
  INSERT INTO procurement.order_line_edit_proof(root_transaction,line_id,order_id,action,snapshot)
  VALUES(txid_current(),row_value.id,row_value.order_id,
    CASE WHEN TG_OP='INSERT' THEN 'add_line' ELSE 'delete_line' END,
    jsonb_build_object('id',row_value.id,'sku_code',row_value.sku_code,
      'qty',row_value.qty::text,'goods_value_byn',row_value.goods_value_byn::text,
      'weight',row_value.weight::text,'volume',row_value.volume::text));
  RETURN NULL;
END $$;
CREATE TRIGGER record_line_edit AFTER INSERT OR DELETE ON procurement.purchase_order_line
FOR EACH ROW EXECUTE FUNCTION procurement.record_line_edit();

CREATE UNIQUE INDEX one_edit_receipt_per_line_action ON procurement.purchase_order_edit_command
  ((CASE WHEN action='save' THEN 'add_line' ELSE action END),
   (CASE WHEN action='save' THEN result::jsonb#>>'{effect,add_line,line,id}'
         ELSE result::jsonb#>>'{effect,line,id}' END))
  WHERE outcome='applied' AND action IN ('add_line','delete_line','save');
CREATE TRIGGER immutable_order_edit_command BEFORE UPDATE OR DELETE
ON procurement.purchase_order_edit_command FOR EACH ROW
EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER no_truncate_order_edit_command BEFORE TRUNCATE
ON procurement.purchase_order_edit_command FOR EACH STATEMENT
EXECUTE FUNCTION accounting.reject_history_mutation();

CREATE OR REPLACE FUNCTION procurement.guard_order_edit_receipt() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE c jsonb:=NEW.command::jsonb; r jsonb:=NEW.result::jsonb; common jsonb; actual_line jsonb;
        line_action text; line_payload jsonb; line_effect jsonb;
BEGIN
  PERFORM 1 FROM accounting.organization WHERE id=NEW.organization_id FOR UPDATE;
  IF NEW.request_key IS DISTINCT FROM (NEW.request_key::uuid)::text
     OR length(btrim(NEW.actor))=0 OR jsonb_typeof(c) IS DISTINCT FROM 'object'
     OR jsonb_typeof(r) IS DISTINCT FROM 'object'
     OR c->'version' IS DISTINCT FROM '1'::jsonb
     OR c->>'request_key' IS DISTINCT FROM NEW.request_key
     OR c->'order_id' IS DISTINCT FROM to_jsonb(NEW.target_order_id)
     OR c->>'action' IS DISTINCT FROM NEW.action
     OR jsonb_typeof(c->'payload') IS DISTINCT FROM 'object'
     OR encode(sha256(convert_to(procurement.order_command_json(c),'UTF8')),'hex')
        IS DISTINCT FROM NEW.command_hash THEN
    RAISE EXCEPTION 'Order edit command identity mismatch';
  END IF;
  common:=jsonb_build_object('version',1,'organization_id',NEW.organization_id,
    'principal',NEW.actor,'request_key',NEW.request_key,'command_hash',NEW.command_hash,
    'order_id',NEW.target_order_id,'action',NEW.action,'outcome',NEW.outcome);
  IF NEW.action='save' AND
    (c->'payload'='{}'::jsonb OR EXISTS (
       SELECT 1 FROM jsonb_object_keys(c->'payload') AS t(step)
       WHERE step NOT IN ('add_line','header','plan','status'))
     OR (NEW.outcome='applied' AND (
       SELECT coalesce(jsonb_object_agg(step,c->'payload'->step),'{}'::jsonb)
       FROM jsonb_object_keys(r->'effect') AS t(step)) IS DISTINCT FROM c->'payload')
     OR (NEW.outcome='applied' AND jsonb_typeof(r->'effect') IS DISTINCT FROM 'object')) THEN
    RAISE EXCEPTION 'Invalid atomic order save';
  END IF;
  IF NEW.outcome='rejected' THEN
    IF NEW.ownership_id IS NOT NULL OR r->>'code' NOT IN
      ('command_abandoned','source_unavailable','order_not_editable','line_unavailable',
       'transition_not_allowed','transport_method_unavailable','sku_catalog_changed')
       OR r->>'code' IS NULL
       OR r IS DISTINCT FROM common || jsonb_build_object('code',r->>'code','no_business_write',true) THEN
      RAISE EXCEPTION 'Order edit rejected receipt mismatch';
    END IF;
  ELSE
    IF NOT EXISTS (SELECT 1 FROM procurement.purchase_ownership
      WHERE id=NEW.ownership_id AND organization_id=NEW.organization_id
        AND kind='order' AND source_id=NEW.target_order_id)
       OR jsonb_typeof(r->'effect') IS DISTINCT FROM 'object'
       OR r IS DISTINCT FROM common || jsonb_build_object('ownership_id',NEW.ownership_id,'effect',r->'effect') THEN
      RAISE EXCEPTION 'Order edit applied receipt ownership mismatch';
    END IF;
    IF NEW.action IN ('add_line','delete_line') OR (NEW.action='save' AND c#>'{payload,add_line}' IS NOT NULL) THEN
      line_action := CASE WHEN NEW.action='save' THEN 'add_line' ELSE NEW.action END;
      line_payload := CASE WHEN NEW.action='save' THEN c#>'{payload,add_line}' ELSE c->'payload' END;
      line_effect := CASE WHEN NEW.action='save' THEN r#>'{effect,add_line}' ELSE r->'effect' END;
      SELECT snapshot INTO actual_line FROM procurement.order_line_edit_proof
        WHERE root_transaction=txid_current() AND order_id=NEW.target_order_id
          AND action=line_action AND to_jsonb(line_id)=line_effect#>'{line,id}';
      IF actual_line IS NULL OR line_effect IS DISTINCT FROM jsonb_build_object('line',actual_line)
         OR (line_action='add_line' AND line_payload - 'sku_id' - 'sku_title' - 'sku_unit'
             IS DISTINCT FROM actual_line-'id')
         OR (line_action='add_line' AND line_payload ? 'sku_id' AND NOT EXISTS
             (SELECT 1 FROM sku s WHERE s.id=(line_payload->>'sku_id')::integer
                AND s.is_active AND s.code=line_payload->>'sku_code'
                AND s.title=line_payload->>'sku_title' AND s.unit=line_payload->>'sku_unit'))
         OR (line_action='delete_line' AND line_payload IS DISTINCT FROM
           jsonb_build_object('line_id',actual_line->'id')) THEN
        RAISE EXCEPTION 'Order edit receipt lacks matching line mutation proof';
      END IF;
    END IF;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER valid_order_edit_receipt BEFORE INSERT ON procurement.purchase_order_edit_command
FOR EACH ROW EXECUTE FUNCTION procurement.guard_order_edit_receipt();
